# Generated by Django 3.2.4 on 2021-06-06 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.CharField(max_length=200, null=True)),
                ('dana', models.CharField(max_length=200, null=True)),
                ('periode', models.CharField(choices=[('2A', '2A'), ('2B', '2B'), ('2C', '2C'), ('2D', '2D'), ('3A', '3A'), ('3B', '3B'), ('3C', '3C'), ('3D', '3D'), ('4A', '4A')], max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Biaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instansi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('alamat', models.CharField(max_length=200, null=True)),
                ('telepon', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('situs', models.CharField(max_length=200, null=True)),
                ('logo', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=200, null=True)),
                ('nama', models.CharField(max_length=200, null=True)),
                ('skpd', models.CharField(max_length=200, null=True)),
                ('pangkat', models.CharField(max_length=200, null=True)),
                ('golongan', models.CharField(choices=[('2A', '2A'), ('2B', '2B'), ('2C', '2C'), ('2D', '2D'), ('3A', '3A'), ('3B', '3B'), ('3C', '3C'), ('3D', '3D'), ('4A', '4A')], max_length=200, null=True)),
                ('jabatan', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Surat_perintah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=200, null=True)),
                ('uraian', models.CharField(max_length=200, null=True)),
                ('tanggal', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('penanggung_jawab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pegawai')),
            ],
            options={
                'ordering': ['nomor'],
            },
        ),
        migrations.CreateModel(
            name='Sppd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=200, null=True)),
                ('perjalanan', models.CharField(max_length=200, null=True)),
                ('tempat_berangkat', models.CharField(max_length=200, null=True)),
                ('tempat_tujuan', models.CharField(max_length=200, null=True)),
                ('tanggal_berangkat', models.DateField(null=True)),
                ('tanggal_kembali', models.DateField(null=True)),
                ('keterangan', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('instansi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.instansi')),
                ('pengikut', models.ManyToManyField(to='myapp.Pegawai')),
                ('surat_perintah', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.surat_perintah')),
            ],
            options={
                'ordering': ['nomor'],
            },
        ),
        migrations.CreateModel(
            name='Rincian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uraian', models.CharField(max_length=200, null=True)),
                ('qty', models.PositiveIntegerField()),
                ('satuan', models.CharField(max_length=200, null=True)),
                ('harga', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('biaya', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.biaya')),
            ],
        ),
        migrations.CreateModel(
            name='Pengeluaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_bukti_pengeluaran', models.CharField(max_length=200, null=True)),
                ('sumber_dana', models.CharField(max_length=200, null=True)),
                ('keperluan', models.CharField(max_length=200, null=True)),
                ('tanggal', models.DateField(null=True)),
                ('keterangan', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('rincian', models.ManyToManyField(to='myapp.Rincian')),
                ('sppd', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.sppd')),
            ],
        ),
    ]
