# Generated by Django 3.2.4 on 2021-06-17 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.CharField(max_length=200, null=True)),
                ('dana', models.CharField(max_length=200, null=True)),
                ('periode', models.CharField(choices=[('Murni', 'Murni'), ('Perubahan', 'Perubahan')], max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instansi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('alamat', models.CharField(max_length=200, null=True)),
                ('telepon', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('situs', models.CharField(max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, default='pemda.png', null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=200, null=True)),
                ('nama', models.CharField(max_length=200, null=True)),
                ('pangkat', models.CharField(max_length=200, null=True)),
                ('golongan', models.CharField(choices=[('IIA', 'IIA'), ('IIB', 'IIB'), ('IIC', 'IIC'), ('IID', 'IID'), ('IIIA', 'IIIA'), ('IIIB', 'IIIB'), ('IIIC', 'IIIC'), ('IIID', 'IIID'), ('IVA', 'IVA'), ('IVB', 'IVB'), ('IVC', 'IVC')], max_length=200, null=True)),
                ('jabatan', models.CharField(max_length=200, null=True)),
                ('status_pegawai', models.CharField(choices=[('PNS', 'PNS'), ('PPPK', 'PPPK'), ('HONORER', 'HONORER')], max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rincian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uraian', models.CharField(max_length=200, null=True)),
                ('kuantitas', models.PositiveIntegerField()),
                ('satuan', models.CharField(choices=[('Hari', 'Hari'), ('Minggu', 'Minggu'), ('Bulan', 'Bulan'), ('Tahun', 'Tahun')], max_length=200, null=True)),
                ('harga', models.IntegerField()),
                ('jumlahnya', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Surat_perintah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=200, null=True)),
                ('uraian', models.CharField(max_length=200, null=True)),
                ('tanggal', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('koordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='myapp.pegawai')),
                ('penanggung_jawab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pegawai')),
                ('pengikut', models.ManyToManyField(blank=True, null=True, related_name='surat_perintahs', to='myapp.Pegawai')),
            ],
            options={
                'ordering': ['nomor'],
            },
        ),
        migrations.CreateModel(
            name='Sppd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=200, null=True)),
                ('maksud_perjalanan', models.CharField(max_length=200, null=True)),
                ('tempat_berangkat', models.CharField(max_length=200, null=True)),
                ('tempat_tujuan', models.CharField(max_length=200, null=True)),
                ('tanggal_berangkat', models.DateField(null=True)),
                ('tanggal_kembali', models.DateField(null=True)),
                ('keterangan', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('surat_perintah', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.surat_perintah')),
            ],
            options={
                'ordering': ['nomor'],
            },
        ),
        migrations.CreateModel(
            name='Pengeluaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_bukti_pengeluaran', models.CharField(max_length=200, null=True)),
                ('sumber_dana', models.CharField(max_length=200, null=True)),
                ('keperluan', models.CharField(max_length=200, null=True)),
                ('tanggal', models.DateField(null=True)),
                ('keterangan', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pegawai')),
                ('rincian', models.ManyToManyField(to='myapp.Rincian')),
                ('sppd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sppd')),
            ],
        ),
    ]
