# Generated by Django 3.2.4 on 2021-06-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rincian',
            old_name='qty',
            new_name='Kuantitas',
        ),
        migrations.RemoveField(
            model_name='instansi',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pegawai',
            name='skpd',
        ),
        migrations.RemoveField(
            model_name='pegawai',
            name='status',
        ),
        migrations.AddField(
            model_name='pegawai',
            name='status_pegawai',
            field=models.CharField(choices=[('PNS', 'PNS'), ('PPPK', 'PPPK'), ('HONORER', 'HONORER')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='anggaran',
            name='periode',
            field=models.CharField(choices=[('Murni', 'Murni'), ('Perubahan', 'Perubahan')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='instansi',
            name='logo',
            field=models.ImageField(blank=True, default='pemda.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='golongan',
            field=models.CharField(choices=[('IIA', 'IIA'), ('IIB', 'IIB'), ('IIC', 'IIC'), ('IID', 'IID'), ('IIIA', 'IIIA'), ('IIIB', 'IIIB'), ('IIIC', 'IIIC'), ('IIID', 'IIID'), ('IVA', 'IVA'), ('IVB', 'IVB'), ('IVC', 'IVC')], max_length=200, null=True),
        ),
    ]
