# Generated by Django 3.2.4 on 2021-06-18 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sppd',
            name='maksud_perjalanan',
        ),
    ]
