# Generated by Django 3.2.4 on 2021-06-08 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rincian',
            name='biaya',
        ),
        migrations.RemoveField(
            model_name='sppd',
            name='instansi',
        ),
        migrations.DeleteModel(
            name='Biaya',
        ),
    ]
