# Generated by Django 3.2.4 on 2021-06-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210608_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sppd',
            name='pengikut',
        ),
        migrations.AddField(
            model_name='surat_perintah',
            name='pengikut',
            field=models.ManyToManyField(blank=True, null=True, related_name='surat_perintahs', to='myapp.Pegawai'),
        ),
        migrations.AlterField(
            model_name='rincian',
            name='satuan',
            field=models.CharField(choices=[('Hari', 'Hari'), ('Minggu', 'Minggu'), ('Bulan', 'Bulan'), ('Tahun', 'Tahun')], max_length=200, null=True),
        ),
    ]
